/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TaskCategory = IDL.Variant({
  'urgency' : IDL.Null,
  'both' : IDL.Null,
  'importance' : IDL.Null,
});
export const DayOfWeek = IDL.Variant({
  'tuesday' : IDL.Null,
  'wednesday' : IDL.Null,
  'saturday' : IDL.Null,
  'thursday' : IDL.Null,
  'sunday' : IDL.Null,
  'friday' : IDL.Null,
  'monday' : IDL.Null,
});
export const TaskInterval = IDL.Variant({
  'custom' : IDL.Vec(DayOfWeek),
  'everyNDays' : IDL.Nat,
  'daily' : IDL.Null,
});
export const Goal = IDL.Record({
  'id' : IDL.Nat,
  'why' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'dueDate' : Time,
  'description' : IDL.Text,
  'category' : TaskCategory,
});
export const RecurringTask = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'interval' : TaskInterval,
  'scheduledTime' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'reminderOffsets' : IDL.Vec(IDL.Int),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DailyTask = IDL.Record({
  'id' : IDL.Nat,
  'day' : Time,
  'title' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'completed' : IDL.Bool,
  'goalId' : IDL.Nat,
  'intensity' : IDL.Nat,
});
export const HourlyLog = IDL.Record({
  'id' : IDL.Nat,
  'day' : Time,
  'hour' : IDL.Int,
  'mood' : IDL.Nat,
  'createdAt' : Time,
  'productivity' : IDL.Nat,
  'user' : IDL.Principal,
  'comment' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHourlyLog' : IDL.Func(
      [Time, IDL.Int, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeDailyTask' : IDL.Func([IDL.Nat], [], []),
  'createGoal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, TaskCategory, Time],
      [IDL.Nat],
      [],
    ),
  'createRecurringTask' : IDL.Func(
      [IDL.Text, IDL.Text, TaskInterval, IDL.Text, IDL.Vec(IDL.Int)],
      [IDL.Nat],
      [],
    ),
  'deleteGoal' : IDL.Func([IDL.Nat], [], []),
  'deleteRecurringTask' : IDL.Func([IDL.Nat], [], []),
  'getAllGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getAllRecurringTasks' : IDL.Func([], [IDL.Vec(RecurringTask)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyTasksForGoal' : IDL.Func([IDL.Nat], [IDL.Vec(DailyTask)], ['query']),
  'getGoal' : IDL.Func([IDL.Nat], [Goal], ['query']),
  'getHourlyLogs' : IDL.Func([Time], [IDL.Vec(HourlyLog)], ['query']),
  'getProcrastinationStats' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
  'getRecurringTask' : IDL.Func([IDL.Nat], [RecurringTask], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasSeenMorningPrompt' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markPromptSeen' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TaskCategory = IDL.Variant({
    'urgency' : IDL.Null,
    'both' : IDL.Null,
    'importance' : IDL.Null,
  });
  const DayOfWeek = IDL.Variant({
    'tuesday' : IDL.Null,
    'wednesday' : IDL.Null,
    'saturday' : IDL.Null,
    'thursday' : IDL.Null,
    'sunday' : IDL.Null,
    'friday' : IDL.Null,
    'monday' : IDL.Null,
  });
  const TaskInterval = IDL.Variant({
    'custom' : IDL.Vec(DayOfWeek),
    'everyNDays' : IDL.Nat,
    'daily' : IDL.Null,
  });
  const Goal = IDL.Record({
    'id' : IDL.Nat,
    'why' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'dueDate' : Time,
    'description' : IDL.Text,
    'category' : TaskCategory,
  });
  const RecurringTask = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'interval' : TaskInterval,
    'scheduledTime' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'reminderOffsets' : IDL.Vec(IDL.Int),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DailyTask = IDL.Record({
    'id' : IDL.Nat,
    'day' : Time,
    'title' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'completed' : IDL.Bool,
    'goalId' : IDL.Nat,
    'intensity' : IDL.Nat,
  });
  const HourlyLog = IDL.Record({
    'id' : IDL.Nat,
    'day' : Time,
    'hour' : IDL.Int,
    'mood' : IDL.Nat,
    'createdAt' : Time,
    'productivity' : IDL.Nat,
    'user' : IDL.Principal,
    'comment' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHourlyLog' : IDL.Func(
        [Time, IDL.Int, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeDailyTask' : IDL.Func([IDL.Nat], [], []),
    'createGoal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, TaskCategory, Time],
        [IDL.Nat],
        [],
      ),
    'createRecurringTask' : IDL.Func(
        [IDL.Text, IDL.Text, TaskInterval, IDL.Text, IDL.Vec(IDL.Int)],
        [IDL.Nat],
        [],
      ),
    'deleteGoal' : IDL.Func([IDL.Nat], [], []),
    'deleteRecurringTask' : IDL.Func([IDL.Nat], [], []),
    'getAllGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getAllRecurringTasks' : IDL.Func([], [IDL.Vec(RecurringTask)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyTasksForGoal' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DailyTask)],
        ['query'],
      ),
    'getGoal' : IDL.Func([IDL.Nat], [Goal], ['query']),
    'getHourlyLogs' : IDL.Func([Time], [IDL.Vec(HourlyLog)], ['query']),
    'getProcrastinationStats' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
    'getRecurringTask' : IDL.Func([IDL.Nat], [RecurringTask], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasSeenMorningPrompt' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markPromptSeen' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };