/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyTask {
  'id' : bigint,
  'day' : Time,
  'title' : string,
  'createdAt' : Time,
  'user' : Principal,
  'completed' : boolean,
  'goalId' : bigint,
  'intensity' : bigint,
}
export type DayOfWeek = { 'tuesday' : null } |
  { 'wednesday' : null } |
  { 'saturday' : null } |
  { 'thursday' : null } |
  { 'sunday' : null } |
  { 'friday' : null } |
  { 'monday' : null };
export interface Goal {
  'id' : bigint,
  'why' : string,
  'title' : string,
  'createdAt' : Time,
  'user' : Principal,
  'dueDate' : Time,
  'description' : string,
  'category' : TaskCategory,
}
export interface HourlyLog {
  'id' : bigint,
  'day' : Time,
  'hour' : bigint,
  'mood' : bigint,
  'createdAt' : Time,
  'productivity' : bigint,
  'user' : Principal,
  'comment' : string,
}
export interface RecurringTask {
  'id' : bigint,
  'title' : string,
  'interval' : TaskInterval,
  'scheduledTime' : string,
  'createdAt' : Time,
  'user' : Principal,
  'description' : string,
  'reminderOffsets' : Array<bigint>,
}
export type TaskCategory = { 'urgency' : null } |
  { 'both' : null } |
  { 'importance' : null };
export type TaskInterval = { 'custom' : Array<DayOfWeek> } |
  { 'everyNDays' : bigint } |
  { 'daily' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHourlyLog' : ActorMethod<[Time, bigint, bigint, bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeDailyTask' : ActorMethod<[bigint], undefined>,
  'createGoal' : ActorMethod<
    [string, string, string, TaskCategory, Time],
    bigint
  >,
  'createRecurringTask' : ActorMethod<
    [string, string, TaskInterval, string, Array<bigint>],
    bigint
  >,
  'deleteGoal' : ActorMethod<[bigint], undefined>,
  'deleteRecurringTask' : ActorMethod<[bigint], undefined>,
  'getAllGoals' : ActorMethod<[], Array<Goal>>,
  'getAllRecurringTasks' : ActorMethod<[], Array<RecurringTask>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyTasksForGoal' : ActorMethod<[bigint], Array<DailyTask>>,
  'getGoal' : ActorMethod<[bigint], Goal>,
  'getHourlyLogs' : ActorMethod<[Time], Array<HourlyLog>>,
  'getProcrastinationStats' : ActorMethod<[], [bigint, bigint]>,
  'getRecurringTask' : ActorMethod<[bigint], RecurringTask>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasSeenMorningPrompt' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markPromptSeen' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];