/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type TaskInterval = {
    __kind__: "custom";
    custom: Array<DayOfWeek>;
} | {
    __kind__: "everyNDays";
    everyNDays: bigint;
} | {
    __kind__: "daily";
    daily: null;
};
export interface RecurringTask {
    id: bigint;
    title: string;
    interval: TaskInterval;
    scheduledTime: string;
    createdAt: Time;
    user: Principal;
    description: string;
    reminderOffsets: Array<bigint>;
}
export interface HourlyLog {
    id: bigint;
    day: Time;
    hour: bigint;
    mood: bigint;
    createdAt: Time;
    productivity: bigint;
    user: Principal;
    comment: string;
}
export interface DailyTask {
    id: bigint;
    day: Time;
    title: string;
    createdAt: Time;
    user: Principal;
    completed: boolean;
    goalId: bigint;
    intensity: bigint;
}
export interface UserProfile {
    name: string;
}
export interface Goal {
    id: bigint;
    why: string;
    title: string;
    createdAt: Time;
    user: Principal;
    dueDate: Time;
    description: string;
    category: TaskCategory;
}
export enum DayOfWeek {
    tuesday = "tuesday",
    wednesday = "wednesday",
    saturday = "saturday",
    thursday = "thursday",
    sunday = "sunday",
    friday = "friday",
    monday = "monday"
}
export enum TaskCategory {
    urgency = "urgency",
    both = "both",
    importance = "importance"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addHourlyLog(day: Time, hour: bigint, mood: bigint, productivity: bigint, comment: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeDailyTask(taskId: bigint): Promise<void>;
    createGoal(title: string, description: string, why: string, category: TaskCategory, dueDate: Time): Promise<bigint>;
    createRecurringTask(title: string, description: string, interval: TaskInterval, scheduledTime: string, reminderOffsets: Array<bigint>): Promise<bigint>;
    getAllGoals(): Promise<Array<Goal>>;
    getAllRecurringTasks(): Promise<Array<RecurringTask>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyTasksForGoal(goalId: bigint): Promise<Array<DailyTask>>;
    getGoal(id: bigint): Promise<Goal>;
    getHourlyLogs(day: Time): Promise<Array<HourlyLog>>;
    getProcrastinationStats(): Promise<[bigint, bigint]>;
    getRecurringTask(id: bigint): Promise<RecurringTask>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasSeenMorningPrompt(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    markPromptSeen(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { DayOfWeek as _DayOfWeek, Goal as _Goal, RecurringTask as _RecurringTask, TaskCategory as _TaskCategory, TaskInterval as _TaskInterval, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addHourlyLog(arg0: Time, arg1: bigint, arg2: bigint, arg3: bigint, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addHourlyLog(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHourlyLog(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeDailyTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeDailyTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeDailyTask(arg0);
            return result;
        }
    }
    async createGoal(arg0: string, arg1: string, arg2: string, arg3: TaskCategory, arg4: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGoal(arg0, arg1, arg2, to_candid_TaskCategory_n3(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGoal(arg0, arg1, arg2, to_candid_TaskCategory_n3(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async createRecurringTask(arg0: string, arg1: string, arg2: TaskInterval, arg3: string, arg4: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecurringTask(arg0, arg1, to_candid_TaskInterval_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecurringTask(arg0, arg1, to_candid_TaskInterval_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async getAllGoals(): Promise<Array<Goal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGoals();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGoals();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRecurringTasks(): Promise<Array<RecurringTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecurringTasks();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecurringTasks();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyTasksForGoal(arg0: bigint): Promise<Array<DailyTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyTasksForGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyTasksForGoal(arg0);
            return result;
        }
    }
    async getGoal(arg0: bigint): Promise<Goal> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoal(arg0);
                return from_candid_Goal_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoal(arg0);
            return from_candid_Goal_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHourlyLogs(arg0: Time): Promise<Array<HourlyLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHourlyLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHourlyLogs(arg0);
            return result;
        }
    }
    async getProcrastinationStats(): Promise<[bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getProcrastinationStats();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProcrastinationStats();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getRecurringTask(arg0: bigint): Promise<RecurringTask> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecurringTask(arg0);
                return from_candid_RecurringTask_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecurringTask(arg0);
            return from_candid_RecurringTask_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasSeenMorningPrompt(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasSeenMorningPrompt();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasSeenMorningPrompt();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markPromptSeen(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markPromptSeen();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPromptSeen();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_DayOfWeek_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DayOfWeek): DayOfWeek {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_RecurringTask_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecurringTask): RecurringTask {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TaskCategory_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskCategory): TaskCategory {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_TaskInterval_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskInterval): TaskInterval {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    why: string;
    title: string;
    createdAt: _Time;
    user: Principal;
    dueDate: _Time;
    description: string;
    category: _TaskCategory;
}): {
    id: bigint;
    why: string;
    title: string;
    createdAt: Time;
    user: Principal;
    dueDate: Time;
    description: string;
    category: TaskCategory;
} {
    return {
        id: value.id,
        why: value.why,
        title: value.title,
        createdAt: value.createdAt,
        user: value.user,
        dueDate: value.dueDate,
        description: value.description,
        category: from_candid_TaskCategory_n13(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    interval: _TaskInterval;
    scheduledTime: string;
    createdAt: _Time;
    user: Principal;
    description: string;
    reminderOffsets: Array<bigint>;
}): {
    id: bigint;
    title: string;
    interval: TaskInterval;
    scheduledTime: string;
    createdAt: Time;
    user: Principal;
    description: string;
    reminderOffsets: Array<bigint>;
} {
    return {
        id: value.id,
        title: value.title,
        interval: from_candid_TaskInterval_n18(_uploadFile, _downloadFile, value.interval),
        scheduledTime: value.scheduledTime,
        createdAt: value.createdAt,
        user: value.user,
        description: value.description,
        reminderOffsets: value.reminderOffsets
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    urgency: null;
} | {
    both: null;
} | {
    importance: null;
}): TaskCategory {
    return "urgency" in value ? TaskCategory.urgency : "both" in value ? TaskCategory.both : "importance" in value ? TaskCategory.importance : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: Array<_DayOfWeek>;
} | {
    everyNDays: bigint;
} | {
    daily: null;
}): {
    __kind__: "custom";
    custom: Array<DayOfWeek>;
} | {
    __kind__: "everyNDays";
    everyNDays: bigint;
} | {
    __kind__: "daily";
    daily: null;
} {
    return "custom" in value ? {
        __kind__: "custom",
        custom: from_candid_vec_n20(_uploadFile, _downloadFile, value.custom)
    } : "everyNDays" in value ? {
        __kind__: "everyNDays",
        everyNDays: value.everyNDays
    } : "daily" in value ? {
        __kind__: "daily",
        daily: value.daily
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
}): DayOfWeek {
    return "tuesday" in value ? DayOfWeek.tuesday : "wednesday" in value ? DayOfWeek.wednesday : "saturday" in value ? DayOfWeek.saturday : "thursday" in value ? DayOfWeek.thursday : "sunday" in value ? DayOfWeek.sunday : "friday" in value ? DayOfWeek.friday : "monday" in value ? DayOfWeek.monday : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Goal>): Array<Goal> {
    return value.map((x)=>from_candid_Goal_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecurringTask>): Array<RecurringTask> {
    return value.map((x)=>from_candid_RecurringTask_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DayOfWeek>): Array<DayOfWeek> {
    return value.map((x)=>from_candid_DayOfWeek_n21(_uploadFile, _downloadFile, x));
}
function to_candid_DayOfWeek_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): _DayOfWeek {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_TaskCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskCategory): _TaskCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TaskInterval_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskInterval): _TaskInterval {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskCategory): {
    urgency: null;
} | {
    both: null;
} | {
    importance: null;
} {
    return value == TaskCategory.urgency ? {
        urgency: null
    } : value == TaskCategory.both ? {
        both: null
    } : value == TaskCategory.importance ? {
        importance: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "custom";
    custom: Array<DayOfWeek>;
} | {
    __kind__: "everyNDays";
    everyNDays: bigint;
} | {
    __kind__: "daily";
    daily: null;
}): {
    custom: Array<_DayOfWeek>;
} | {
    everyNDays: bigint;
} | {
    daily: null;
} {
    return value.__kind__ === "custom" ? {
        custom: to_candid_vec_n7(_uploadFile, _downloadFile, value.custom)
    } : value.__kind__ === "everyNDays" ? {
        everyNDays: value.everyNDays
    } : value.__kind__ === "daily" ? {
        daily: value.daily
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
} {
    return value == DayOfWeek.tuesday ? {
        tuesday: null
    } : value == DayOfWeek.wednesday ? {
        wednesday: null
    } : value == DayOfWeek.saturday ? {
        saturday: null
    } : value == DayOfWeek.thursday ? {
        thursday: null
    } : value == DayOfWeek.sunday ? {
        sunday: null
    } : value == DayOfWeek.friday ? {
        friday: null
    } : value == DayOfWeek.monday ? {
        monday: null
    } : value;
}
function to_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DayOfWeek>): Array<_DayOfWeek> {
    return value.map((x)=>to_candid_DayOfWeek_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
